### ISSUE TITLE
为啥不基于 segross' UnrealImGui plugin？

### ISSUE THREAD

**Issue by marshal-it** [Eragon-Brisingr/ImGui_WS#1]
有一些其他的工具基于segross' UnrealImGui plugin。
想用你这个，就没办法共存了

**Comment by Eragon-Brisingr** [comment]
segross' UnrealImGui plugin从虚幻挺早的版本开始制作的，看了下代码结构有些混乱了，评估后觉得自己从头写可以用少量的代码达到他的功能，没必要去维护他那套机制。
https://github.com/Eragon-Brisingr/ImGui_WS/blob/master/README_ZH.md#%E7%BB%98%E5%88%B6%E4%BA%8B%E4%BB%B6
用这个回调应该能简单接入别的插件的imgui绘制方法（但是没法用到布局系统了
