### ISSUE TITLE
支持UE4.27?有啥依赖吗？直接拖入插件编译失败

### ISSUE THREAD

**Issue by zdszx** [Eragon-Brisingr/ImGui_WS#3]

**Comment by Eragon-Brisingr** [comment]
理论支持，应该只是一些API对不上，有详细的报错吗？

**Comment by zdszx** [comment]
<img width="776" alt="image" src="https://github.com/Eragon-Brisingr/ImGui_WS/assets/43289834/7eda9ee2-4134-4440-bb52-acdce0685785">

**Comment by Eragon-Brisingr** [comment]
输出页签下能发第一个报错吗？

**Comment by zdszx** [comment]
<img width="1015" alt="image" src="https://github.com/Eragon-Brisingr/ImGui_WS/assets/43289834/081bf797-5f85-4ae5-b8f4-4cd4985f60ef">

**Comment by Eragon-Brisingr** [comment]
你按着它报错改，删了UPROPERTY中的Config后编译看看还有报错吗？有的话接着改

**Comment by Eragon-Brisingr** [comment]
@zdszx 问题解决了吗？解决了麻烦关闭下issue

**Comment by zdszx** [comment]
斯。。。能不能私发我一个使用这个插件的样例工程，效果真的很好，奈何我手残没复现出来😭😭



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月29日(周四) 晚上7:19
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Eragon-Brisingr/ImGui_WS] 支持UE4.27?有啥依赖吗？直接拖入插件编译失败 (Issue #3)




 
@zdszx 问题解决了吗？解决了麻烦关闭下issue

**Comment by Eragon-Brisingr** [comment]
你是指4.27的吗？我本地没有4.27的版本。假如是UE5.1.1的话直接下载[ImGui_WS-5.1.1](https://github.com/Eragon-Brisingr/ImGui_WS/releases/tag/UE-5.1.1)放到插件目录即可开启网页
