### ISSUE TITLE
编译时候这个头文件报错了

### ISSUE THREAD

**Issue by yingnierxiao** [Eragon-Brisingr/ImGui_WS#5]
https://github.com/Eragon-Brisingr/ImGui_WS/blob/0e566481666c78a06a096c91f54c498d35adbb3e/Source/ImGui/UnrealCore/Private/UnrealImGuiLibrary.cpp#L7

**Comment by Eragon-Brisingr** [comment]
5.4才有的头文件，5.3把这行注释了就行

**Comment by Eragon-Brisingr** [comment]
@yingnierxiao 假如编译过了没啥问题麻烦关闭下这个issue~

**Comment by yingnierxiao** [comment]
嗯确实移除可以，是不是考虑加下宏
